# Generated by Django 4.2.7 on 2025-09-10 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('tipo', models.CharField(default='retiro', max_length=30)),
                ('estado', models.CharField(default='pendiente', max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='ordenes.orden')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
